"""
How to Graph DNA to AMINO ACIDS
Given: DNA Sequence and Amino acids sequence put into a table of DNA to AMINO ACIDS with numbered amino acids  
remove spaces 
"""
    
# import matplotlib.pyplot as plt
# import numpy as np
# # pGEX-4T-1-UNC76-MYC
# aa = "MSPILGYWKIKGLVQPTRLLLEYLEEKYEEHLYERDEGDKWRNKKFELGLEFPNLPYYIDGDVKLTQSMAIIRYIADKHNMLGGCPKERAEISMLEGAVLDIRYGVSRIAYSKDFETLKVDFLSKLPEMLKMFEDRLCHKTYLNGDHVTHPDFMLYDALDVVLYMDPMCLDAFPKLVCFKKRIEAIPQIDKYLKSSKYIAWPLQGWQATFGGGDHPPKSDLVPRGSPEFMRDLGTKMAELKFEAPLAKFEETDEWGGCDFISSQNAINDTLNLNLKDSSAGGKPDATKLRLLEDAVRDAHVSKNGGGVVGGGAGSISPNCNTLQGGSLIEIGLSDVGLVPGEGAGVGLDGLEKRSLAVGDHVDNFTETFGGSLEDLVNTFDEKITKCFGNYEENVEELAPVQVRSQEEIMNECQMWWTITGNFGNILPIDWSKSYTRQMHMPTLNLGQNHTKQQQQNRNQQQQLHNQSHQAYPHTNGLGSGSGSGLDAQTPGDEFNDLTSEDEAVANDLDMHALILNGLNGDMDDQPIKTVEEVIKEIDDIMDEAESPLDEPETCDSEVIEKAREVLGAPLYAEKLQYLTTTQLNELYMEMEVLIQELSETLINELALRDELEFEKELKNSFISLLLAVQNKRRQYHVEKKRGKFQGPEPKYLTTVIPYHLENGTPNNQSLQVLIKILKAINEDSPTVPALLTDYILKVLCPTWRPLGGSGGGSGEQKLISEEDLAAAS"
# dna = "atgtcccctatactaggttattggaaaattaagggccttgtgcaacccactcgacttcttttggaatatcttgaagaaaaatatgaagagcatttgtatgagcgcgatgaaggtgataaatggcgaaacaaaaagtttgaattgggtttggagtttcccaatcttccttattatattgatggtgatgttaaattaacacagtctatggccatcatacgttatatagctgacaagcacaacatgttgggtggttgtccaaaagagcgtgcagagatttcaatgcttgaaggagcggttttggatattagatacggtgtttcgagaattgcatatagtaaagactttgaaactctcaaagttgattttcttagcaagctacctgaaatgctgaaaatgttcgaagatcgtttatgtcataaaacatatttaaatggtgatcatgtaacccatcctgacttcatgttgtatgacgctcttgatgttgttttatacatggacccaatgtgcctggatgcgttcccaaaattagtttgttttaaaaaacgtattgaagctatcccacaaattgataagtacttgaaatccagcaagtatatagcatggcctttgcagggctggcaagccacgtttggtggtggcgaccatcctccaaaatcggatctggttccgcgtggatccccggaattcatgcgtgacctcggcaccaaaatggccgagctaaaattcgaggctccattggcaaagttcgaggaaacggacgagtggggcggctgcgacttcatctcgagtcagaatgccataaacgacacgctcaacctgaatctgaaggactcctccgccggcggcaagccggatgccaccaagctgcggctcctagaggatgctgtacgcgatgcgcacgtgagcaagaacggaggaggagtagtgggaggaggagctggctccattagccccaattgcaacacgctccagggtgggtcgcttattgaaatcggcctgtccgatgtgggattggtgccgggcgagggagccggcgttggtctggacggtctggagaagcgctccctggccgtcggcgaccatgtggacaacttcacggagaccttcggcggaagtctggaggatctggtcaatacgttcgacgaaaagataaccaagtgtttcggcaactacgaagagaacgtcgaggagctggctccggtgcaggtgcgcagccaggaggagatcatgaacgaatgccaaatgtggtggaccatcacaggaaactttggcaacattctgcccatcgactggtccaagtcgtacacccgtcagatgcacatgcccacactgaatctgggccagaaccacacgaagcagcagcagcagaatcgcaaccagcagcagcagttgcacaaccagagccatcaggcgtatccacacaccaacggtttgggatccggatccggatccggcctggatgcccagactccgggcgatgagttcaacgatctgaccagtgaggacgaggcggtggccaacgatttggacatgcacgccctcatccttaacggcttgaacggtgacatggacgaccagccgattaagacggtagaggaggtgatcaaggagatcgacgacatcatggacgaggccgagagcccgctggacgagccggagacctgcgattcggaggtgatcgagaaggcgcgagaggtgctgggcgcccccctctatgcggaaaaactgcaatatctgaccacgacacagctgaacgagctgtacatggagatggaggtgctgatccaggagctgagcgagacgttgatcaacgagctggccctgcgcgacgagctggagttcgagaaggagctgaagaactcgttcatctctctgctcctcgccgttcagaacaaaaggcggcagtaccatgtggagaagaagcgcggcaagttccagggtcccgagcccaagtacttgaccacagtcattccgtatcacctggagaacggcacgcccaacaatcagtctctgcaggtcctgatcaagattctcaaggccatcaacgaggacagcccgacggttccggccctccttacggactacatcctgaaggtgctctgccctacatggcggccgctgggtggttctggtggtggttctggtGAACAAAAACTCATCTCAGAAGAGGATCTGgcggccgcatcg"

import pandas as pd

# Amino acid sequence
protein_seq = "MSPILGYWKIKGLVQPTRLLLEYLEEKYEEHLYERDEGDKWRNKKFELGLEFPNLPYYIDGDVKLTQSMAIIRYIADKHNMLGGCPKERAEISMLEGAVLDIRYGVSRIAYSKDFETLKVDFLSKLPEMLKMFEDRLCHKTYLNGDHVTHPDFMLYDALDVVLYMDPMCLDAFPKLVCFKKRIEAIPQIDKYLKSSKYIAWPLQGWQATFGGGDHPPKSDLVPRGSPEFMRDLGTKMAELKFEAPLAKFEETDEWGGCDFISSQNAINDTLNLNLKDSSAGGKPDATKLRLLEDAVRDAHVSKNGGGVVGGGAGSISPNCNTLQGGSLIEIGLSDVGLVPGEGAGVGLDGLEKRSLAVGDHVDNFTETFGGSLEDLVNTFDEKITKCFGNYEENVEELAPVQVRSQEEIMNECQMWWTITGNFGNILPIDWSKSYTRQMHMPTLNLGQNHTKQQQQNRNQQQQLHNQSHQAYPHTNGLGSGSGSGLDAQTPGDEFNDLTSEDEAVANDLDMHALILNGLNGDMDDQPIKTVEEVIKEIDDIMDEAESPLDEPETCDSEVIEKAREVLGAPLYAEKLQYLTTTQLNELYMEMEVLIQELSETLINELALRDELEFEKELKNSFISLLLAVQNKRRQYHVEKKRGKFQGPEPKYLTTVIPYHLENGTPNNQSLQVLIKILKAINEDSPTVPALLTDYILKVLCPTWRPLGGSGGGSGEQKLISEEDLAAAS"

# DNA sequence (clean + uppercase)
dna_seq = """atgtcccctatactaggttattggaaaattaagggccttgtgcaacccactcgacttcttttggaatatcttgaagaaaaatatgaagagcatttgtatgagcgcgatgaaggtgataaatggcgaaacaaaaagtttgaattgggtttggagtttcccaatcttccttattatattgatggtgatgttaaattaacacagtctatggccatcatacgttatatagctgacaagcacaacatgttgggtggttgtccaaaagagcgtgcagagatttcaatgcttgaaggagcggttttggatattagatacggtgtttcgagaattgcatatagtaaagactttgaaactctcaaagttgattttcttagcaagctacctgaaatgctgaaaatgttcgaagatcgtttatgtcataaaacatatttaaatggtgatcatgtaacccatcctgacttcatgttgtatgacgctcttgatgttgttttatacatggacccaatgtgcctggatgcgttcccaaaattagtttgttttaaaaaacgtattgaagctatcccacaaattgataagtacttgaaatccagcaagtatatagcatggcctttgcagggctggcaagccacgtttggtggtggcgaccatcctccaaaatcggatctggttccgcgtggatccccggaattcatgcgtgacctcggcaccaaaatggccgagctaaaattcgaggctccattggcaaagttcgaggaaacggacgagtggggcggctgcgacttcatctcgagtcagaatgccataaacgacacgctcaacctgaatctgaaggactcctccgccggcggcaagccggatgccaccaagctgcggctcctagaggatgctgtacgcgatgcgcacgtgagcaagaacggaggaggagtagtgggaggaggagctggctccattagccccaattgcaacacgctccagggtgggtcgcttattgaaatcggcctgtccgatgtgggattggtgccgggcgagggagccggcgttggtctggacggtctggagaagcgctccctggccgtcggcgaccatgtggacaacttcacggagaccttcggcggaagtctggaggatctggtcaatacgttcgacgaaaagataaccaagtgtttcggcaactacgaagagaacgtcgaggagctggctccggtgcaggtgcgcagccaggaggagatcatgaacgaatgccaaatgtggtggaccatcacaggaaactttggcaacattctgcccatcgactggtccaagtcgtacacccgtcagatgcacatgcccacactgaatctgggccagaaccacacgaagcagcagcagcagaatcgcaaccagcagcagcagttgcacaaccagagccatcaggcgtatccacacaccaacggtttgggatccggatccggatccggcctggatgcccagactccgggcgatgagttcaacgatctgaccagtgaggacgaggcggtggccaacgatttggacatgcacgccctcatccttaacggcttgaacggtgacatggacgaccagccgattaagacggtagaggaggtgatcaaggagatcgacgacatcatggacgaggccgagagcccgctggacgagccggagacctgcgattcggaggtgatcgagaaggcgcgagaggtgctgggcgcccccctctatgcggaaaaactgcaatatctgaccacgacacagctgaacgagctgtacatggagatggaggtgctgatccaggagctgagcgagacgttgatcaacgagctggccctgcgcgacgagctggagttcgagaaggagctgaagaactcgttcatctctctgctcctcgccgttcagaacaaaaggcggcagtaccatgtggagaagaagcgcggcaagttccagggtcccgagcccaagtacttgaccacagtcattccgtatcacctggagaacggcacgcccaacaatcagtctctgcaggtcctgatcaagattctcaaggccatcaacgaggacagcccgacggttccggccctccttacggactacatcctgaaggtgctctgccctacatggcggccgctgggtggttctggtggtggttctggtgaacaaaaactcatctcagaagaggatctggcggccgcatcg""".upper()

# Remove non-ATGC characters (if any)
dna_seq = ''.join([base for base in dna_seq if base in "ATGC"])

# Split DNA into codons
codons = [dna_seq[i:i+3] for i in range(0, len(protein_seq)*3, 3)]

# Create DataFrame
df = pd.DataFrame({
    "Position": range(1, len(protein_seq) + 1),
    "Amino Acid": list(protein_seq),
    "Codon": codons
})

print(df)
# Save to CSV
df.to_csv("amino_acid_codon_table.csv", index=False)

print("CSV file saved as amino_acid_codon_table.csv")